//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortalEverthing.Localizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Cake {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Cake() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebPortalEverthing.Localizations.Cake", typeof(Cake).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя создателя.
        /// </summary>
        public static string Admin_Creator_Name {
            get {
                return ResourceManager.GetString("Admin_Creator_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string Admin_Delete {
            get {
                return ResourceManager.GetString("Admin_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        public static string Admin_Description {
            get {
                return ResourceManager.GetString("Admin_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Картинка.
        /// </summary>
        public static string Admin_Image {
            get {
                return ResourceManager.GetString("Admin_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string Admin_Name_Cake {
            get {
                return ResourceManager.GetString("Admin_Name_Cake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена.
        /// </summary>
        public static string Admin_Price {
            get {
                return ResourceManager.GetString("Admin_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить торт.
        /// </summary>
        public static string Layout_Cake_Add_Cake {
            get {
                return ResourceManager.GetString("Layout_Cake_Add_Cake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить связь.
        /// </summary>
        public static string Layout_Cake_Add_Link {
            get {
                return ResourceManager.GetString("Layout_Cake_Add_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить магазин.
        /// </summary>
        public static string Layout_Cake_Add_Magazin {
            get {
                return ResourceManager.GetString("Layout_Cake_Add_Magazin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Админ.
        /// </summary>
        public static string Layout_Cake_Admin {
            get {
                return ResourceManager.GetString("Layout_Cake_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все торты.
        /// </summary>
        public static string Layout_Cake_All_Cakes {
            get {
                return ResourceManager.GetString("Layout_Cake_All_Cakes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главная.
        /// </summary>
        public static string Layout_Cake_Main {
            get {
                return ResourceManager.GetString("Layout_Cake_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мои творения.
        /// </summary>
        public static string Layout_Cake_My_Creation {
            get {
                return ResourceManager.GetString("Layout_Cake_My_Creation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Торты.
        /// </summary>
        public static string Link_Cakes {
            get {
                return ResourceManager.GetString("Link_Cakes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Связать.
        /// </summary>
        public static string Link_Link {
            get {
                return ResourceManager.GetString("Link_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Магазины.
        /// </summary>
        public static string Link_Magazins {
            get {
                return ResourceManager.GetString("Link_Magazins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string My_Creation_Delete {
            get {
                return ResourceManager.GetString("My_Creation_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        public static string My_Creation_Description {
            get {
                return ResourceManager.GetString("My_Creation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Картинка.
        /// </summary>
        public static string My_Creation_Image {
            get {
                return ResourceManager.GetString("My_Creation_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string My_Creation_Name {
            get {
                return ResourceManager.GetString("My_Creation_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена.
        /// </summary>
        public static string My_Creation_Price {
            get {
                return ResourceManager.GetString("My_Creation_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обн.
        /// </summary>
        public static string My_Creation_Update {
            get {
                return ResourceManager.GetString("My_Creation_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аватар.
        /// </summary>
        public static string Profile_Avatar {
            get {
                return ResourceManager.GetString("Profile_Avatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отпр.
        /// </summary>
        public static string Profile_Send {
            get {
                return ResourceManager.GetString("Profile_Send", resourceCulture);
            }
        }
    }
}
