//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortalEverthing.Localizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Coffe {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Coffe() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebPortalEverthing.Localizations.Coffe", typeof(Coffe).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бренд.
        /// </summary>
        public static string Coffe_Brand {
            get {
                return ResourceManager.GetString("Coffe_Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Купить.
        /// </summary>
        public static string Coffe_Buy {
            get {
                return ResourceManager.GetString("Coffe_Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В Корзину.
        /// </summary>
        public static string Coffe_Cart {
            get {
                return ResourceManager.GetString("Coffe_Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фильтры.
        /// </summary>
        public static string Coffe_Filter {
            get {
                return ResourceManager.GetString("Coffe_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стоимость.
        /// </summary>
        public static string Coffe_Filter_Cost {
            get {
                return ResourceManager.GetString("Coffe_Filter_Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена.
        /// </summary>
        public static string Coffe_Filter_Price {
            get {
                return ResourceManager.GetString("Coffe_Filter_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык.
        /// </summary>
        public static string Coffe_Language {
            get {
                return ResourceManager.GetString("Coffe_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Карьера.
        /// </summary>
        public static string Footer_Career {
            get {
                return ResourceManager.GetString("Footer_Career", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наши контакты.
        /// </summary>
        public static string Footer_Contact {
            get {
                return ResourceManager.GetString("Footer_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Авторское право.
        /// </summary>
        public static string Footer_Copyright {
            get {
                return ResourceManager.GetString("Footer_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользовательское Cоглашение.
        /// </summary>
        public static string Footer_Policy {
            get {
                return ResourceManager.GetString("Footer_Policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все права защищены.
        /// </summary>
        public static string Footer_Rights {
            get {
                return ResourceManager.GetString("Footer_Rights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наши Сервисы.
        /// </summary>
        public static string Footer_Service {
            get {
                return ResourceManager.GetString("Footer_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Каталог.
        /// </summary>
        public static string Layout_Catalog {
            get {
                return ResourceManager.GetString("Layout_Catalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кофе.
        /// </summary>
        public static string Layout_Coffe {
            get {
                return ResourceManager.GetString("Layout_Coffe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оборудование.
        /// </summary>
        public static string Layout_Equipment {
            get {
                return ResourceManager.GetString("Layout_Equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О нас.
        /// </summary>
        public static string Layout_Reviews {
            get {
                return ResourceManager.GetString("Layout_Reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Корзина.
        /// </summary>
        public static string Layout_Thing {
            get {
                return ResourceManager.GetString("Layout_Thing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На портал.
        /// </summary>
        public static string Layout_ToPortal {
            get {
                return ResourceManager.GetString("Layout_ToPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аватар.
        /// </summary>
        public static string Profile_Avatar {
            get {
                return ResourceManager.GetString("Profile_Avatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моя корзина.
        /// </summary>
        public static string Profile_Cart {
            get {
                return ResourceManager.GetString("Profile_Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установить готовый аватар.
        /// </summary>
        public static string Profile_Default_Avatar {
            get {
                return ResourceManager.GetString("Profile_Default_Avatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить аватар.
        /// </summary>
        public static string Profile_Update_Avatar {
            get {
                return ResourceManager.GetString("Profile_Update_Avatar", resourceCulture);
            }
        }
    }
}
