//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortalEverthing.Localizations {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Home {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Home() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebPortalEverthing.Localizations.Home", typeof(Home).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тык.
        /// </summary>
        public static string Anime_Link_Text {
            get {
                return ResourceManager.GetString("Anime_Link_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на За тортиками.
        /// </summary>
        public static string Cake_Link_Text {
            get {
                return ResourceManager.GetString("Cake_Link_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сюда.
        /// </summary>
        public static string Coffe_Link_Text {
            get {
                return ResourceManager.GetString("Coffe_Link_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Если вы хотите посмотреть каталог аниме.
        /// </summary>
        public static string Home_AnimeCatalog {
            get {
                return ResourceManager.GetString("Home_AnimeCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вам сюда.
        /// </summary>
        public static string Home_AnimeCatalog_LinkText {
            get {
                return ResourceManager.GetString("Home_AnimeCatalog_LinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Если вам хочется полюбоваться на аниме девочек то вас.
        /// </summary>
        public static string Home_AnimeGirlDesc {
            get {
                return ResourceManager.GetString("Home_AnimeGirlDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Если вы хотите заказать кофе, и всё что для него прилагается, то вам.
        /// </summary>
        public static string Home_CoffeShopDesc {
            get {
                return ResourceManager.GetString("Home_CoffeShopDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Привет.
        /// </summary>
        public static string Home_Greatings {
            get {
                return ResourceManager.GetString("Home_Greatings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Гость.
        /// </summary>
        public static string Home_Guest {
            get {
                return ResourceManager.GetString("Home_Guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Главная.
        /// </summary>
        public static string Home_HomePage {
            get {
                return ResourceManager.GetString("Home_HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Залогиниться.
        /// </summary>
        public static string Home_Login {
            get {
                return ResourceManager.GetString("Home_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выйти.
        /// </summary>
        public static string Home_Logout {
            get {
                return ResourceManager.GetString("Home_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не знаешь что посмотреть на выходных? Тогда тебе.
        /// </summary>
        public static string Home_MoviePosterDesc {
            get {
                return ResourceManager.GetString("Home_MoviePosterDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уведомления.
        /// </summary>
        public static string Home_Notification {
            get {
                return ResourceManager.GetString("Home_Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Зарегестироваться.
        /// </summary>
        public static string Home_Registration {
            get {
                return ResourceManager.GetString("Home_Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователи.
        /// </summary>
        public static string Home_Users {
            get {
                return ResourceManager.GetString("Home_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на сюда.
        /// </summary>
        public static string MoviePoster_Link_Text {
            get {
                return ResourceManager.GetString("MoviePoster_Link_Text", resourceCulture);
            }
        }
    }
}
